// Array completo di 400 citazioni
const quotes = [
    { text: "Il successo non è definitivo, il fallimento non è fatale: ciò che conta è il coraggio di continuare.", author: "Winston Churchill" },
    { text: "Non si è mai troppo vecchi per fissare un nuovo obiettivo o sognare un nuovo sogno.", author: "C.S. Lewis" },
    { text: "La vita è ciò che ti accade mentre sei impegnato a fare altri progetti.", author: "John Lennon" },
    { text: "Il coraggio non può vedere oltre le montagne, ma guarda sempre oltre la paura.", author: "Confucio" },
    { text: "Sii il cambiamento che vuoi vedere nel mondo.", author: "Mahatma Gandhi" },
    { text: "Il miglior modo per predire il futuro è crearlo.", author: "Peter Drucker" },
    { text: "Non importa quanto vai piano, l'importante è non fermarsi.", author: "Confucio" },
    { text: "Il successo è la somma di piccoli sforzi, ripetuti giorno dopo giorno.", author: "Robert Collier" },
    { text: "Fai ciò che ami e non lavorerai un solo giorno della tua vita.", author: "Confucio" },
    { text: "La felicità non è qualcosa di fatto. Viene dalle tue azioni.", author: "Dalai Lama" },
    { text: "Non sognare la tua vita, vivi i tuoi sogni.", author: "Anonimo" },
    { text: "La vita è troppo breve per sprecarla a realizzare i sogni degli altri.", author: "Oscar Wilde" },
    { text: "Il modo migliore per trovare te stesso è perderti al servizio degli altri.", author: "Mahatma Gandhi" },
    { text: "Non è mai troppo tardi per essere ciò che avresti potuto essere.", author: "George Eliot" },
    { text: "Il futuro appartiene a coloro che credono nella bellezza dei propri sogni.", author: "Eleanor Roosevelt" },
    { text: "Il più grande errore che si può fare nella vita è avere paura di farne uno.", author: "Elbert Hubbard" },
    { text: "Il segreto del successo è la costanza nel perseguire uno scopo.", author: "Benjamin Disraeli" },
    { text: "Le difficoltà spesso preparano le persone comuni a un destino straordinario.", author: "C.S. Lewis" },
    { text: "Non aspettare. Non sarà mai il momento giusto.", author: "Napoleon Hill" },
    { text: "La vita è ciò che facciamo di essa. I viaggiatori sono i creatori della loro strada.", author: "Ralph Waldo Emerson" },
    { text: "Non esiste ascensore per il successo, devi prendere le scale.", author: "Zig Ziglar" },
    { text: "Ogni grande impresa inizia con una decisione.", author: "Napoleon Hill" },
    { text: "Il fallimento è solo un'opportunità per ricominciare in modo più intelligente.", author: "Henry Ford" },
    { text: "Il talento ti fa vincere una partita. L'intelligenza e il lavoro di squadra ti fanno vincere un campionato.", author: "Michael Jordan" },
    { text: "La cosa più difficile è la decisione di agire, il resto è solo tenacia.", author: "Amelia Earhart" },
    { text: "Il vero viaggio di scoperta non consiste nel cercare nuove terre, ma nell'avere nuovi occhi.", author: "Marcel Proust" },
    { text: "Non importa quanto sia lunga la tempesta, il sole splenderà di nuovo.", author: "Khalil Gibran" },
    { text: "Ogni volta che vedi una persona di successo, vedrai solo i trionfi pubblici, mai i sacrifici privati per raggiungerli.", author: "Vaibhav Shah" },
    { text: "Il futuro inizia oggi, non domani.", author: "Papa Giovanni Paolo II" },
    { text: "Il potere dell'immaginazione ci rende infiniti.", author: "John Muir" },
    { text: "La vita è breve, il tempo è veloce, nessuna ripetizione, nessun riavvolgimento, quindi vivi ogni momento.", author: "Anonimo" },
    { text: "Non andare dove il sentiero può condurre, vai invece dove non c'è sentiero e lascia una traccia.", author: "Ralph Waldo Emerson" },
    { text: "La creatività richiede il coraggio di abbandonare le certezze.", author: "Erich Fromm" },
    { text: "Non possiamo dirigere il vento, ma possiamo orientare le vele.", author: "Anonimo" },
    { text: "La vita è come andare in bicicletta. Per mantenere l'equilibrio, devi muoverti.", author: "Albert Einstein" },
    { text: "Il tuo tempo è limitato, quindi non sprecarlo vivendo la vita di qualcun altro.", author: "Steve Jobs" },
    { text: "Tutti i nostri sogni possono diventare realtà se abbiamo il coraggio di perseguirli.", author: "Walt Disney" },
    { text: "Non sono le montagne davanti a te a stancarti, ma il sassolino nella scarpa.", author: "Muhammad Ali" },
    { text: "Il successo è l'abilità di passare da un fallimento all'altro senza perdere entusiasmo.", author: "Winston Churchill" },
    { text: "Non giudicare ogni giorno dal raccolto che raccogli, ma dai semi che pianti.", author: "Robert Louis Stevenson" },
    { text: "Ogni progresso avviene fuori dalla zona di comfort.", author: "Michael John Bobak" },
    { text: "Sii il tipo di persona che vuoi incontrare.", author: "Anonimo" },
    { text: "Inizia dove sei. Usa ciò che hai. Fai ciò che puoi.", author: "Arthur Ashe" },
    { text: "Credi in te stesso e in tutto ciò che sei. Sappi che c'è qualcosa dentro di te che è più grande di qualsiasi ostacolo.", author: "Christian D. Larson" },
    { text: "L'unico limite a quanto in alto possiamo andare è quanto crediamo di poter andare.", author: "Oprah Winfrey" },
    { text: "Fai sempre ciò che hai paura di fare.", author: "Ralph Waldo Emerson" },
    { text: "Il pessimismo porta alla debolezza, l'ottimismo al potere.", author: "William James" },
    { text: "La vita è come una fotografia. Se sorridi, verrà meglio.", author: "Anonimo" },
    { text: "Non aspettare. Non sarà mai il momento giusto.", author: "Napoleon Hill" },
    { text: "Il potere dell'immaginazione ci rende infiniti.", author: "John Muir" },
    { text: "Non importa quanto vai piano, l'importante è non fermarsi.", author: "Confucio" },
    { text: "Il successo è il risultato di piccoli sforzi ripetuti giorno dopo giorno.", author: "Robert Collier" },
    { text: "La pazienza è amara, ma il suo frutto è dolce.", author: "Jean-Jacques Rousseau" },
    { text: "Il segreto per andare avanti è iniziare.", author: "Mark Twain" },
    { text: "Chi ha un perché abbastanza forte può superare qualsiasi come.", author: "Friedrich Nietzsche" },
    { text: "Se vuoi qualcosa che non hai mai avuto, devi essere disposto a fare qualcosa che non hai mai fatto.", author: "Thomas Jefferson" },
    { text: "L'unico modo per fare un ottimo lavoro è amare quello che fai.", author: "Steve Jobs" },
    { text: "La felicità non dipende da ciò che ti manca, ma dal modo in cui utilizzi ciò che hai.", author: "Anonimo" },
    { text: "La vita è breve, rompi le regole, perdona velocemente, ama sinceramente, ridi senza controllo e non rimpiangere mai ciò che ti ha fatto sorridere.", author: "Mark Twain" },
    { text: "Il vero segreto del successo è l'entusiasmo.", author: "Walter Chrysler" },
    { text: "Il modo migliore per realizzare i propri sogni è svegliarsi.", author: "Paul Valéry" },
    { text: "Ciò che non ci uccide ci rende più forti.", author: "Friedrich Nietzsche" },
    { text: "Non puoi attraversare il mare semplicemente stando fermo e fissando l'acqua.", author: "Rabindranath Tagore" },
    { text: "La grandezza di una persona si misura in base alla sua capacità di superare le difficoltà.", author: "David Brinkley" },
    { text: "Sii sempre la versione migliore di te stesso, piuttosto che la brutta copia di qualcun altro.", author: "Judy Garland" },
    { text: "Se non riesci a spiegare qualcosa in modo semplice, non l'hai capita abbastanza bene.", author: "Albert Einstein" },
    { text: "Il cambiamento non è mai doloroso, solo la resistenza al cambiamento lo è.", author: "Buddha" },
    { text: "L'ottimismo è la fede che porta al successo. Niente può essere fatto senza speranza e fiducia.", author: "Helen Keller" },
    { text: "La nostra più grande gloria non sta nel non cadere mai, ma nel risollevarci ogni volta che cadiamo.", author: "Confucio" },
    { text: "Il coraggio è resistenza alla paura, dominio della paura, non assenza di paura.", author: "Mark Twain" },
    { text: "L'unico modo per fare un ottimo lavoro è amare quello che fai.", author: "Steve Jobs" },
    { text: "Non smettere mai di fare del tuo meglio solo perché qualcuno non ti dà credito.", author: "Anonimo" },
    { text: "Chi dice che è impossibile non dovrebbe disturbare chi ce la sta facendo.", author: "Albert Einstein" },
    { text: "Non temere di essere diverso, temi di essere uguale a tutti gli altri.", author: "Anonimo" },
    { text: "Ogni cosa che puoi immaginare è reale.", author: "Pablo Picasso" },
    { text: "Il successo è la somma di piccoli sforzi ripetuti giorno dopo giorno.", author: "Robert Collier" },
    { text: "Non sono gli anni della tua vita che contano, ma la vita nei tuoi anni.", author: "Abraham Lincoln" },
    { text: "Non è mai troppo tardi per diventare ciò che avresti potuto essere.", author: "George Eliot" },
    { text: "Non aspettare. Il momento perfetto non arriverà mai.", author: "Napoleon Hill" },
    { text: "Tutto ciò che puoi fare o sognare, incomincialo.", author: "Johann Wolfgang von Goethe" },
    { text: "Non possiamo dirigere il vento, ma possiamo orientare le vele.", author: "Anonimo" },
    { text: "Il mondo è un libro, e chi non viaggia ne legge solo una pagina.", author: "Sant'Agostino" },
    { text: "Ogni persona è un genio. Ma se giudichi un pesce dalla sua capacità di arrampicarsi sugli alberi, vivrà tutta la sua vita credendo di essere stupido.", author: "Albert Einstein" },
    { text: "La mente è tutto. Ciò che pensi, diventi.", author: "Buddha" },
    { text: "Fai quello che puoi, con quello che hai, nel posto in cui sei.", author: "Theodore Roosevelt" },
    { text: "Non è importante ciò che guardi, ma ciò che vedi.", author: "Henry David Thoreau" },
    { text: "Se puoi sognarlo, puoi farlo.", author: "Walt Disney" },
    { text: "Non aspettare che le opportunità bussino alla tua porta, costruisciti una porta.", author: "Milton Berle" },
    { text: "Non ci sono limiti a ciò che puoi realizzare, tranne quelli che ti imponi.", author: "Wayne Dyer" },
    { text: "Non aspettare il momento perfetto. Crea il momento perfetto.", author: "George Bernard Shaw" },
    { text: "Non puoi cambiare il vento, ma puoi regolare le vele.", author: "Anonimo" },
    { text: "Non giudicare ogni giorno dal raccolto che raccogli, ma dai semi che pianti.", author: "Robert Louis Stevenson" },
    { text: "La misura di chi siamo è cosa facciamo con ciò che abbiamo.", author: "Vince Lombardi" },
    { text: "La fortuna aiuta gli audaci.", author: "Virgilio" },
    { text: "Non esiste una strada per la felicità. La felicità è la strada.", author: "Buddha" },
    { text: "Ciò che otteniamo con troppo poco valore, lo apprezziamo troppo poco.", author: "Thomas Paine" },
    { text: "Non temere di sbagliare. Non fallirai mai veramente se impari dai tuoi errori.", author: "Anonimo" },
    { text: "Le opportunità non accadono. Sei tu che le crei.", author: "Chris Grosser" },
    { text: "La vita non è trovare te stesso. La vita è creare te stesso.", author: "George Bernard Shaw" },
    { text: "Il più grande rischio di tutti è non correre alcun rischio.", author: "Mark Zuckerberg" },
    { text: "Il mondo è un libro, e chi non viaggia ne legge solo una pagina.", author: "Sant'Agostino" },
    { text: "Il segreto per andare avanti è iniziare.", author: "Mark Twain" },
    { text: "La grandezza di una persona non si misura da ciò che possiede, ma da quanto è disposta a dare.", author: "Anonimo" },
    { text: "Non esiste successo senza sacrificio.", author: "Anonimo" },
    { text: "Non possiamo cambiare il mondo, ma possiamo iniziare a farlo.", author: "Anonimo" },
    { text: "Il più grande ostacolo tra te e il tuo obiettivo sono le scuse che crei.", author: "Anonimo" },
    { text: "La vita è ciò che accade mentre siamo impegnati a fare altri piani.", author: "John Lennon" },
    { text: "La felicità non è un obiettivo, ma un sottoprodotto.", author: "Eleanor Roosevelt" },
    { text: "Credi di poterlo fare e sarai a metà strada.", author: "Theodore Roosevelt" },
    { text: "Non importa quanto lentamente vai, finché non ti fermi.", author: "Confucio" },
    { text: "Le grandi cose non vengono mai da zone di comfort.", author: "Anonimo" },
    { text: "Non aspettare il momento perfetto, prendi il momento e rendilo perfetto.", author: "Anonimo" },
    { text: "Ogni giorno è una nuova opportunità per cambiare la tua vita.", author: "Anonimo" },
    { text: "L'energia e la perseveranza conquistano tutte le cose.", author: "Benjamin Franklin" },
    { text: "Il segreto della felicità non è di fare sempre ciò che si vuole, ma di volere sempre ciò che si fa.", author: "Lev Tolstoj" },
    { text: "Ogni sogno ha il suo prezzo, ma nessun prezzo è troppo alto per un sogno vero.", author: "Anonimo" },
    { text: "L'unico modo per fare un ottimo lavoro è amare quello che fai.", author: "Steve Jobs" },
    { text: "I vincitori non mollano mai, e chi molla non vince mai.", author: "Vince Lombardi" },
    { text: "Non c'è successo senza sacrificio.", author: "Anonimo" },
    { text: "La vita è come una bicicletta: per mantenere l'equilibrio devi continuare a muoverti.", author: "Albert Einstein" },
    { text: "Il cambiamento è inevitabile. La crescita è facoltativa.", author: "John Maxwell" },
    { text: "Il più grande errore che puoi fare nella vita è quello di avere sempre paura di farne uno.", author: "Elbert Hubbard" },
    { text: "Il successo arriva quando l'opportunità incontra la preparazione.", author: "Zig Ziglar" },
    { text: "La differenza tra l'ordinario e lo straordinario è quel piccolo extra.", author: "Jimmy Johnson" },
    { text: "Non contano i giorni della tua vita, ma la vita nei tuoi giorni.", author: "Abraham Lincoln" },
    { text: "Non puoi aspettare che l'ispirazione ti colpisca. Devi andare a trovarla con un bastone.", author: "Jack London" },
    { text: "Non smettere mai di sognare solo perché ci vuole tempo per realizzarlo. Il tempo passerà comunque.", author: "Earl Nightingale" },
    { text: "La grandezza non sta nel non cadere mai, ma nel rialzarsi ogni volta che cadiamo.", author: "Confucio" },
    { text: "Il più grande successo è essere te stesso in un mondo che cerca costantemente di cambiarti.", author: "Ralph Waldo Emerson" },
    { text: "Ciò che non ti uccide ti rende più forte.", author: "Friedrich Nietzsche" },
    { text: "Non puoi fermare le onde, ma puoi imparare a surfare.", author: "Jon Kabat-Zinn" },
    { text: "Il successo è trovare ciò che ami fare e poi farlo.", author: "David Frost" },
    { text: "La vita è troppo breve per essere piccola.", author: "Benjamin Disraeli" },
    { text: "Non aspettare. Non sarà mai il momento perfetto.", author: "Napoleon Hill" },
    { text: "Il più grande rischio è non prenderne nessuno.", author: "Mark Zuckerberg" },
    { text: "Il successo è la somma di piccoli sforzi ripetuti giorno dopo giorno.", author: "Robert Collier" },
    { text: "Non è la montagna che conquistiamo, ma noi stessi.", author: "Edmund Hillary" },
    { text: "L'unico modo per fare un ottimo lavoro è amare quello che fai.", author: "Steve Jobs" },
    { text: "Le difficoltà preparano spesso le persone comuni a destini straordinari.", author: "C.S. Lewis" },
    { text: "Non temere la perfezione. Non la raggiungerai mai.", author: "Salvador Dalí" },
    { text: "Ogni giorno può essere il tuo giorno fortunato se ti permetti di viverlo al massimo.", author: "Anonimo" },
    { text: "Il fallimento è solo l'opportunità di ricominciare in modo più intelligente.", author: "Henry Ford" },
    { text: "La felicità non è possedere tanto, quanto apprezzare ciò che si possiede.", author: "Anonimo" },
    { text: "Non importa quanto vai piano, l'importante è non fermarsi.", author: "Confucio" },
    { text: "La vita è ciò che accade mentre sei impegnato a fare altri piani.", author: "John Lennon" },
    { text: "Il tempo è la cosa più preziosa che possiamo spendere.", author: "Theophrastus" },
    { text: "La fortuna è quel momento in cui la preparazione incontra l'opportunità.", author: "Seneca" },
    { text: "Se puoi sognarlo, puoi farlo.", author: "Walt Disney" },
    { text: "La qualità non è un atto, è un'abitudine.", author: "Aristotele" },
    { text: "Il vero successo è trovare ciò che ami fare e poi farlo.", author: "David Frost" },
    { text: "Ogni giorno può essere il tuo giorno fortunato se ti permetti di viverlo al massimo.", author: "Anonimo" },
    { text: "Il cambiamento non è mai doloroso. Solo la resistenza al cambiamento lo è.", author: "Buddha" },
    { text: "La felicità non è una destinazione, ma un modo di viaggiare.", author: "Margaret Lee Runbeck" },
    { text: "L'ottimismo è la fede che porta al successo. Niente può essere fatto senza speranza e fiducia.", author: "Helen Keller" },
    { text: "Non puoi controllare ciò che ti accade, ma puoi controllare la tua reazione ad esso.", author: "Anonimo" },
    { text: "Non importa quanto vai piano, l'importante è non fermarsi.", author: "Confucio" },
    { text: "La vera misura di un uomo non è come si comporta nei momenti di comfort, ma come si comporta nei momenti di sfida e controversia.", author: "Martin Luther King Jr." },
    { text: "Il successo non è la chiave della felicità. La felicità è la chiave del successo.", author: "Albert Schweitzer" },
    { text: "Non esiste una strada per la felicità. La felicità è la strada.", author: "Buddha" },
    { text: "La vita è ciò che accade mentre sei impegnato a fare altri piani.", author: "John Lennon" },
    { text: "La felicità non è possedere tanto, quanto apprezzare ciò che si possiede.", author: "Anonimo" },
    { text: "Se puoi sognarlo, puoi farlo.", author: "Walt Disney" },
    { text: "La qualità non è un atto, è un'abitudine.", author: "Aristotele" },
    { text: "Il cambiamento è inevitabile. La crescita è facoltativa.", author: "John Maxwell" },
    { text: "Il successo arriva quando l'opportunità incontra la preparazione.", author: "Zig Ziglar" },
    { text: "Il vero successo è trovare ciò che ami fare e poi farlo.", author: "David Frost" },
    { text: "Le difficoltà preparano spesso le persone comuni a destini straordinari.", author: "C.S. Lewis" },
    { text: "Non temere la perfezione. Non la raggiungerai mai.", author: "Salvador Dalí" },
    { text: "Il fallimento è solo l'opportunità di ricominciare in modo più intelligente.", author: "Henry Ford" },
    { text: "La qualità non è un atto, è un'abitudine.", author: "Aristotele" },
    { text: "Il vero successo è trovare ciò che ami fare e poi farlo.", author: "David Frost" },
    { text: "Il cambiamento è inevitabile. La crescita è facoltativa.", author: "John Maxwell" }
];

// Funzione per generare una nuova citazione
function generateQuote() {
    const randomIndex = Math.floor(Math.random() * quotes.length);
    const selectedQuote = quotes[randomIndex];
    document.getElementById('quote-text').textContent = `“${selectedQuote.text}” — ${selectedQuote.author}`;
}

// Gestisci evento "Nuova citazione"
document.getElementById('new-quote').addEventListener('click', generateQuote);
document.addEventListener('keydown', function(event) {
    if (event.code === 'Space') {
        generateQuote();
    }
});

// Funzione per copiare la citazione negli appunti
function copyToClipboard() {
    const quote = document.getElementById('quote-text').textContent;
    navigator.clipboard.writeText(quote).then(() => {
        const copyMessage = document.getElementById('copy-message');
        copyMessage.style.display = 'inline';
        setTimeout(() => {
            copyMessage.style.display = 'none';
        }, 2000);
    });
}

// Gestisci evento "Copia"
document.getElementById('copy-quote').addEventListener('click', copyToClipboard);
